name: Build & Deploy PWA to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inject cache version
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "Injecting version: $VERSION"
          sed -i "s/__CACHE_VERSION__/$VERSION/" service-worker.js

      - uses: actions/upload-pages-artifact@v4
        with:
          path: .   # ou "dist", se você tiver build separado

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
